version: "3.9"

services:
  exam-helper:
    build: .
    container_name: exam-helper
    env_file: .env
    volumes:
      - ./data/screenshots:/app/data/screenshots:ro
      - ./data/answers:/app/data/answers
    restart: unless-stopped
