services:
  exam-helper:
    image: immoralnull/exam-helper:latest
    container_name: exam-helper
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
